export type CatalogType =
    | "card-names"
    | "artist-names"
    | "word-bank"
    | "creature-types"
    | "planeswalker-types"
    | "land-types"
    | "artifact-types"
    | "enchantment-types"
    | "spell-types"
    | "powers"
    | "toughnesses"
    | "loyalties"
    | "watermarks"
    | "keyword-abilities"
    | "keyword-actions"
    | "ability-words";
